name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code
    
    - name: Build C#
      run: dotnet build

    - name: C# tests
      run: dotnet test

    - name: Move
      run: cd .\DotnetTemplate.Web\

    - name: Install packages
      run: npm install

    - name: Build Typescript
      run: npm run build

    - name: Lint Typescript
      run: npm run lint

    - name: Typescript tests
      run: npm t        